# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ShowAlllistWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ShowAlllistWidget.setGeometry(QtCore.QRect(50, 60, 261, 381))
        self.ShowAlllistWidget.setObjectName("ShowAlllistWidget")
        self.Selected1 = QtWidgets.QLabel(self.centralwidget)
        self.Selected1.setGeometry(QtCore.QRect(50, 20, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Selected1.setFont(font)
        self.Selected1.setObjectName("Selected1")
        self.pushButton_Add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Add.setGeometry(QtCore.QRect(220, 450, 93, 28))
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.ShowFavlistWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ShowFavlistWidget.setGeometry(QtCore.QRect(50, 490, 261, 241))
        self.ShowFavlistWidget.setObjectName("ShowFavlistWidget")
        self.pushButton_remove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remove.setGeometry(QtCore.QRect(210, 750, 93, 28))
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.Selected2 = QtWidgets.QLabel(self.centralwidget)
        self.Selected2.setGeometry(QtCore.QRect(320, 490, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Selected2.setFont(font)
        self.Selected2.setObjectName("Selected2")
        self.ShowReclistWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ShowReclistWidget.setGeometry(QtCore.QRect(350, 60, 251, 381))
        self.ShowReclistWidget.setObjectName("ShowReclistWidget")
        self.Recommended = QtWidgets.QLabel(self.centralwidget)
        self.Recommended.setGeometry(QtCore.QRect(350, 20, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Recommended.setFont(font)
        self.Recommended.setObjectName("Recommended")
        self.recommend_button = QtWidgets.QPushButton(self.centralwidget)
        self.recommend_button.setGeometry(QtCore.QRect(320, 540, 251, 41))
        self.recommend_button.setText("")
        self.recommend_button.setObjectName("recommend_button")
        self.RecButlabel = QtWidgets.QLabel(self.centralwidget)
        self.RecButlabel.setGeometry(QtCore.QRect(330, 530, 231, 61))
        self.RecButlabel.setObjectName("RecButlabel")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(640, 350, 421, 311))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 309))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.titleLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(19)
        self.titleLabel.setFont(font)
        self.titleLabel.setText("")
        self.titleLabel.setObjectName("titleLabel")
        self.descriptionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descriptionLabel.setGeometry(QtCore.QRect(4, 145, 411, 161))
        self.descriptionLabel.setText("")
        self.descriptionLabel.setObjectName("descriptionLabel")
        
        self.genreLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.genreLabel.setGeometry(QtCore.QRect(0, 90, 421, 31))
        self.genreLabel.setText("")
        self.genreLabel.setObjectName("genreLabel")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(650, 720, 431, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.ratingSelector = QtWidgets.QSpinBox(self.centralwidget)
        self.ratingSelector.setGeometry(QtCore.QRect(540, 730, 42, 22))
        self.ratingSelector.setObjectName("ratingSelector")
        self.ratingMovie = QtWidgets.QLabel(self.centralwidget)
        self.ratingMovie.setGeometry(QtCore.QRect(350, 706, 171, 61))
        self.ratingMovie.setText("")
        self.ratingMovie.setObjectName("ratingMovie")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 670, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.recommend_button_user = QtWidgets.QPushButton(self.centralwidget)
        self.recommend_button_user.setGeometry(QtCore.QRect(320, 600, 251, 41))
        self.recommend_button_user.setText("")
        self.recommend_button_user.setObjectName("recommend_button_user")
        self.RecButlabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.RecButlabel_2.setGeometry(QtCore.QRect(330, 590, 231, 61))
        self.RecButlabel_2.setObjectName("RecButlabel_2")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(644, 50, 411, 261))
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Selected1.setText(_translate("MainWindow", "Selected Movie"))
        self.pushButton_Add.setText(_translate("MainWindow", "Add"))
        self.pushButton_remove.setText(_translate("MainWindow", "Remove"))
        self.Selected2.setText(_translate("MainWindow", "Selected Movie"))
        self.Recommended.setText(_translate("MainWindow", "Recommended"))
        self.RecButlabel.setText(_translate("MainWindow", "Recommend based on selected movie"))
        self.label_2.setText(_translate("MainWindow", "Select your rating for this movie"))
        self.RecButlabel_2.setText(_translate("MainWindow", "Recommend based on collab filter"))

